services:

  mongodb:
    image: mongo
    container_name: mongodb1
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - mongodb_data:/data/db

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - "8091:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_ADMINUSERNAME: user
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
      ME_CONFIG_BASICAUTH_USERNAME: user
      ME_CONFIG_BASICAUTH_PASSWORD: root
    depends_on:
      - mongodb
volumes:
  mongodb_data:


  # docker-compose up -d                    == run
  # docker-compose down                     == destroy
  # docker ps -a | grep control-center      == Check if a container exists
  # docker rm control-center                == remove it

  # MongoDb
  # mongosh "mongodb://user:root@localhost:27017/admin"
  # use milton
  # db.createUser({
  #  user: "user",
  #  pwd: "root",
  #  roles: [ { role: "readWrite", db: "milton" } ]
  #})

# docker pull splunk/splunk:9.2.0
#  docker run --platform linux/amd64 \
#  -p 8000:8000 \
#  -e SPLUNK_START_ARGS=--accept-license \
#  -e SPLUNK_GENERAL_TERMS=--accept-sgt-current-at-splunk-com \
#  -e SPLUNK_PASSWORD=YourSecurePassword123 \
#  splunk/splunk:latest
